apiVersion: v1
kind: Secret
metadata:
    name: dashboard-api
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:CET/lpaS0hINTA==,iv:k268o8uyJ7BOwMfZCK6+SLzCgOWW3dX6HKsPutK7I+M=,tag:h9f/I2ZtW7SKt+lw4D+v8A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Zb5PFcprKApCDg==,iv:bKA+VYg0CXOI32+80lLowWXfwAYLYanTQxD376Kyk/0=,tag:qkrVNe6UebzvSdZyRM2F7Q==,type:str]
sops:
    age:
        - recipient: age15zcnnd23pszetpkd5cxjy3mm96qzr7fcajspxh346e2lqr3m5p6q2jmrta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QzUxVXdnT1QzR014ZGZY
            d1lzRUh3bkNHUk9OY0NTY3VBWVFYTi9sdjAwCldtZlc0RDFoeHVLN1VNaktuaU41
            UnJlQzY4Y0FQOTFsUEUxcS9JYVM4U1UKLS0tIEdnMEJwNysyd0RFRUVJMFYxQXRy
            Qm9GZng2S0dSQ3E0MHpjQldtbCtCeEkKOUIJCF0XNxEBGFRoPbJlP02SxOFrsNcU
            spHOhlq9BEvb5/Wbq+ZKLFB4F4d82g9bNKksoD0jFpShXI4xjr2g9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T16:10:45Z"
    mac: ENC[AES256_GCM,data:OR/he/yIAm5oEIGllPRqzO4E0IZDObqriPNR2mjKILSTvY5XaXLbtDqCOuKK+5Ptz6l4/5D6lEJCRc/ereyh0b6H/QfU3kMbiQVlh/xImjR4ein1jYp3h0vnmR5FBO+2qsZt+FDeIjVJg1bF8LQQW7FLq5WSqCU8cgsyckyLU6c=,iv:qtPzroHWXJEMxMb3CHlzetcrrR+BkQTOO6IS9LBf37I=,tag:kthwkI7h/CclcL1za9qG8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
